[DAT-17989] Add tableLocation functionality to createTable
liquibase/liquibase-databricks pull request #154
Opened 2024-07-18 10:10 UTC by vitaliimak

2024-07-18 12:00 UTC, filipelautert requested changes

2024-07-18 12:00 UTC, filipelautert commented on src/main/java/liquibase/ext/databricks/sqlgenerator/CreateTableGeneratorDatabricks.java
>              if (!StringUtils.isEmpty(thisStatement.getTableLocation())) {
Do you think this `tableLocation` field still makes sense?

2024-07-18 13:28 UTC, filipelautert approved these changes

2024-07-19 10:50 UTC, KushnirykOleh approved these changes

2024-08-21 10:52 UTC, merged